spring:
  application:
    name: APIGateway
  boot:
    admin:
      client:
        url: http://localhost:9090
  cloud:
    gateway:
      server:
        webmvc:                    # ← add this level
          routes:
            # ==========================
            # LOGIN MICROSERVICE
            # ==========================
            - id: user-login-service
              uri: lb://UserLoginMicroservice-1
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            # ==========================
            # MESSAGE MICROSERVICE
            # ==========================
            - id: user-msg-service
              uri: lb://UserMsgMicroservice-1
              predicates:
                - Path=/msg/**
              filters:
                - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
