spring:
  boot:
    admin:
      client:
        url: http://localhost:9090

  datasource:
    url: jdbc:mysql://localhost:3306/Aug15
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
